version: '3.7'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-hackathon
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=Asia/Kolkata
      - NODE_ENV=production
      - EXECUTIONS_MODE=regular
    volumes:
      - ./workflows:/home/node/.n8n/workflows
      - ./data:/home/node/.n8n
    env_file:
      - .env
